Repository ruimarinho/bitcoin-core, pull requests merged in 2022-07, with the labels that each got.

#126 Handle non-JSON response
  src/logging/request-obfuscator.js
  test/logging/request-obfuscator_test.js
Labels: bug

#123 Add support for bitcoin@0.19.0 RPC methods
  dist/src/errors/rpc-error.js
  dist/src/errors/standard-error.js
  dist/src/index.js
  dist/src/methods.js
  src/errors/rpc-error.js
  src/errors/standard-error.js
  src/index.js
  src/methods.js
  test/client_test.js
  test/config/index.js
Labels: enhancement

#106 Remove Babel
  .babelrc
  .dockerignore
  .github/workflows/tests.yaml
  .npmignore
  dist/src/errors/rpc-error.js
  dist/src/errors/standard-error.js
  dist/src/index.js
  dist/src/logging/request-logger.js
  dist/src/logging/request-obfuscator.js
  dist/src/methods.js
  dist/src/parser.js
  dist/src/requester.js
  package.json
  src/errors/rpc-error.js
  src/errors/standard-error.js
  src/index.js
  src/logging/request-logger.js
  src/logging/request-obfuscator.js
  src/methods.js
  src/parser.js
  src/requester.js
  test/client_test.js
  test/config/index.js
  test/errors/rpc-error_test.js
  test/logging/request-obfuscator_test.js
  test/multi_wallet_test.js
  test/parser_test.js
  test/requester_test.js
  test/rest_test.js
  test/single_wallet_test.js
  test/utils/help-parser-util.js
Labels: enhancement, breaking change

#142 Add support for bitcoin@>0.19.0 RPC methods
  src/methods.js
Labels: enhancement
